import Navbar from "../component/navbar/Navbar";
import "./global.css";

export const metadata = {
  title: "setting-nextjs",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="my-containerxxx">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
